name: java CD

on:
  pull_request:
    branches: [ "master" ]
    types: [ closed ]

jobs:

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: CI
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_ID_RSA }}
        script: |
          sudo apt update
          sudo apt install docker.io -y
          sudo docker pull ${{ needs.CI.outputs.GITHUB_TAG }}
          sudo docker run -d ${{ needs.CI.outputs.GITHUB_TAG }}

